### ISSUE TITLE
Clipped Atmosphere Layer

### ISSUE THREAD

**Issue by ndorigatti** [NASAWorldWind/WorldWindAndroid#1]
It seems that Atmoshpere Layer is clipped the wrong way sometimes. Here it is in the CameraView example a couple of screenshots showing it (Using Nexus6p or Motorola MotoX with Android M both).

Just opened CameraView example and rotated a bit on left-right from the default view.

![screenshot_20160331-124355](https://cloud.githubusercontent.com/assets/3414365/14173683/bbe8c176-f73f-11e5-9c08-768146b0ba8e.png)
![screenshot_20160331-124434](https://cloud.githubusercontent.com/assets/3414365/14173684/bbeca548-f73f-11e5-81aa-87540ad64d28.png)

**Comment by pdavidc** [comment]
Nicola, Thanks for bringing this to our attention. Just to clarify, the atmosphere layer is an experimental feature in the examples project that we're still developing. We'll be sure to look into this.

**Comment by ndorigatti** [comment]
ah-ha I see now why! Then it's ok. Thanks for the feedback, and let me say that v0.1 is very good and smooth! As soon as i have some time I will try to customize a bit the examples and give some feedback.

**Comment by pdavidc** [comment]
@ndorigatti Would you please try the latest code in the develop branch, and let us know whether or not the issue is fixed?

**Comment by ndorigatti** [comment]
@pdavidc I can't check from the source code, but I've downloaded the tutorials apk from the latest daily build (3101) and I don't see the atmosphere layer, so can't confirm regarding the issue. Anyway, i tried the basic globe in examples that have the atmosphere layer and I can't see the issue there 👍

**Comment by Sufaev** [comment]
@pdavidc Will Atmosphere layer go inside of worldwind.aar in case of successfully bug fix?

**Comment by pdavidc** [comment]
@ndorigatti Thank you for checking. The examples APK from the daily build contains the fixed atmosphere layer. Given that, I'll consider this issue fixed.

@Sufaev We'll evaluate this layer for inclusion in the core library.
