### ISSUE TITLE
GitHub release notes

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#101]
Provide release notes and a changelog for World Wind Android versioned releases. GitHub milestones provide both: release notes are given by the milestone description, and a changelog is the list of closed issues associated with a milestone. Milestones and releases are loosely associated by a common version string "vA.B.C", which is used both as the tag name and as the milestone title.

**Comment by zglueck** [comment]
273a658e9e7af2134bdf9a044b7cba7c5eae57d1 automates the generation of a CHANGELOG.md file which is uploaded to GitHub releases during a tagged release. The CHANGELOG.md contains the tag, date, milestone description, and list of closed issues associated with the milestone.
