### ISSUE TITLE
Depth-only drawing mode

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#132]
Establish architectural support for depth-only drawing mode. Extend WorldWind's existing architecture to enable drawing only the depth fragments in a scene from a specified perspective.

This establishes a foundational capability for line of sight (#130), and will be one of the key capabilities used to capturing the scene's depth values from a perspective. 

Depth-only drawing mode, like picking, draws the terrain regardless of what's in the LayerList. Layers that draw images and shapes on terrain do nothing during depth-only drawing mode. Shapes that draw objects in the plane of the screen also do nothing. This leaves terrain and 3D shapes to draw depth values into the depth buffer.

**Comment by pdavidc** [comment]
Closes #130

**Comment by zglueck** [comment]
Terrain’s existing architecture and a simplified initial implementation of line of site allowed for a reduction in the scope of this pull request. The "specified perspective" information and interface was no longer required to implement the depth-only drawing.
