### ISSUE TITLE
Perspective render-to-texture

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#133]
Establish the capability to render the WorldWind scene from a specified perspective into an offscreen framebuffer texture. This capability supports capture of both RGBA fragments and depth fragments.

It must be possible to utilize the depth-only drawing mode (#132) to capture perspective depth values in an efficient manner.

**Comment by pdavidc** [comment]
Closes #130

**Comment by zglueck** [comment]
Terrain’s existing architecture and simplified initial implementation of line of site allowed for a reduction in the scope of this issue. The offscreen framebuffer texture was added in 3e4ce7b and supports both RGBA and depth fragments.
