### ISSUE TITLE
Ellipse / SurfaceEllipse

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#18]
Display of an ellipse in 3D and an ellipse draped on the terrain surface. From the COE requirements document:

Circle
- Ability to display a circle features
- Coordinate (lat,lon,altitude)
- Radius
- Line Thickness, Line Color, Dashed lines , Dotted line, Line Alpha, Fill Color, Fill Alpha, Text Label
- Altitude mode

Ellipse 
- Point with major radius, minor radius, and rotation
- Coordinate (lat,lon,altitude)
- Major radius
- Minor radius
- Rotation in degrees
- Line Thickness, Line Color, Dashed lines , Dotted line, Line Alpha, Fill Color, Fill Alpha, Text Label
- Altitude mode

**Comment by pdavidc** [comment]
We've established an initial ellipse shape and corresponding tutorial within the WorldWindAndroid source code. We'll create an easier to use tutorial on worldwind.arc.nasa.gov soon. In the meantime, the in-code tutorial can be found in on GitHub:
https://github.com/NASAWorldWind/WorldWindAndroid/blob/develop/worldwind-tutorials/src/main/java/gov/nasa/worldwindx/EllipseFragment.java

@JACochran the initial Ellipse is ready for integration into the EMP repository. We're working on adjustments that increase the ellipse's level of detail, which will be available prior to your next release.

**Comment by zglueck** [comment]
@JACochran, we've updated the Ellipse implementation in pr #201. If possible, we suggest it be integrated into the EMP release.

**Comment by pdavidc** [comment]
@rsupnekar @JACochran @jrummel, we've implemented enhancements to WorldWindAndroid's Ellipse shape:
• Dynamic level of detail #204 
• Enhanced geometric precision for small ellipses #205

Please try these in EMP and let us know how it works there. We're working on a final enhancement: reducing the memory used by WorldWindAndroid's Ellipse. We'll let you know when that's ready to try in EMP.

**Comment by zglueck** [comment]
All COE requirements are satisfied with the exception of integrated label; however, WWA provides labels as a separate capability.
