### ISSUE TITLE
Terrain following paths with constant longitude can disappear

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#185]
### Description

Path shapes configured with a constant longitude, path type LINEAR, altitude mode CLAMP_TO_GROUND and terrain following enabled may disappear, depending on the path's longitude.

### Steps to Reproduce

The following Path configuration demonstrates the issue at longitude 45 degrees.

```java
Path path = new Path(Arrays.asList(
    Position.fromDegrees(45, -160, 0),
    Position.fromDegrees(45, 0, 0)));
path.setAltitudeMode(WorldWind.CLAMP_TO_GROUND);
path.setPathType(WorldWind.LINEAR);
path.setFollowTerrain(true);
```
### Additional Information

Relates to missioncommand/emp3-android#359
Potentially relates to missioncommand/emp3-android#358

**Comment by rsupnekar** [comment]
No we tested yesterday and still have a problem.

**Comment by rsupnekar** [comment]
Here's a screenshot.  The longitude at 90 is now visible, but note the blurring above latitude 45 has come back.
![screenshot from 2017-12-13 15-28-17](https://user-images.githubusercontent.com/25460036/33960967-6939b352-e01a-11e7-9e27-ba5d0ea15718.png)

**Comment by pdavidc** [comment]
Thanks @rsupnekar. Differences in line detail are a side effect of how WWAndroid draws terrain following lines. As you zoom in the EMP test app, the detail difference should resolve, but then may reappear again at various zoom distances.

We have an improvement in mind that will resolve this, but it'll take time to implement. Feel free to get in touch over the phone if you'd like to discuss possibilities.

**Comment by rsupnekar** [comment]
Thanks.  I will close our issue #359.  #358 is still an issue above +/- ~85 degrees.  I don't know how important those latitudes are.  Some maps, like OSM don't have data for those at all.
