### ISSUE TITLE
How to make the worldwind background transparent?

### ISSUE THREAD

**Issue by q200892907** [NASAWorldWind/WorldWindAndroid#203]
How to make the worldwind background transparent?

**Comment by zglueck** [comment]
You need to provide a EGLConfig override to the WorldWindow constructor. See #89 and #57 for implementations which customize the EGLConfig for transparency.

**Comment by q200892907** [comment]
@zglueck I used the #89 and #57 method, but I can't make the background transparent!
I set the setZOrderOnTop(true) background to be transparent, but WorldWind is at the top of the view, blocking some of the UI.
