### ISSUE TITLE
Global terrain and vertical exaggeration

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#33]
Display of the basic virtual globe with terrain and optional vertical exaggeration.

**Comment by pdavidc** [comment]
Established initial support for global terrain and vertical exaggeration in commit b1a242a. This capability includes:
- Terrain defined by a set of elevation coverages attached to WorldWindow
- Elevation coverages completely replaceable and configurable by the application
- Zero, one, or multiple elevation coverages. Multiple coverages are composited automatically on the client
- Optional vertical exaggeration control
- WCS 1.0.0 elevation coverage support (see #51)
- Default elevation coverage using the global elevation service at NASA Ames

**Comment by Sufaev** [comment]
After moving cameraToLookAt from Globe to Navigator there is a problem to calculate lookAt range in the custom drawables based on rendering context.

Before refactoring it was possible to call renderingContext.globe.cameraToLookAt (renderingContext.camera, lookAt).

Is it possible to add navigator into rendering context?

**Comment by Sufaev** [comment]
May be you can add lookAt value into renderingContext? Then currently protected method cameraToLookAt and navigator itself will not be necessary in renderingContext.

Main problem is that my MilStd2525TacticalGraphics logics required lookAt.range to calculate map scale for symbol rendering and after refactoring of code according to task #33 it is not possible to get lookAt.range now in any way.

**Comment by pdavidc** [comment]
@Sufaev Would you please create a new issue to track this request? Separate but related topics in the same thread aren't productive.

Thanks for providing context here. Knowing that you need range to control display of MIL-STD-2525 graphics is critical.
