### ISSUE TITLE
WMTS image layer (NSG profile)

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#38]
Retrieval and display of imagery from an OGC Web Map Tile Services conforming to the NSG profile.

**Comment by zglueck** [comment]
Limited TileMatrix support of WMTS is available in the develop branch, commit bcd6309.

A full capabilities document parser is provided as well as ```LayerFactory``` functions for generating layers from WMTS servers.

Only EPSG:4326 and CRS84 projections with quad subdivision tile matrices are supported as of commit bcd6309.
