### ISSUE TITLE
WCS elevations

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#51]
Retrieval and display of elevations from an OGC Web Coverage Service incorporated into the globe's terrain.

**Comment by Sufaev** [comment]
Hello!

When do you plan to add ElevationModel interface, its reference usage in BasicGlobe and elevations request in Tessellator->assembleTilePoints method?

I am building some project based on WorldWind and want to clarify, should I do it myself or you plan to add this functionality it in a few month?

Do you accept contributors in this project? May be my team can help to add this feature.

**Comment by pdavidc** [comment]
Hi @Sufaev,

The NASA World Wind team will be incorporating Android terrain in the next few months. It'll be fully integrated as an ElevationModel as you described. We'll associate this issue with a dated milestone soon.

**Comment by pdavidc** [comment]
We've started work on Android terrain and elevation models, and expect to deliver an initial version by the end of March 2016. The initial version will use the OGC Web Coverage Service protocol, not WMS as originally indicated by this issue. We've updated the issue to reflect that change.

**Comment by zglueck** [comment]
Initial WCS capability added in ca2daa6c2d71127ac7e41f626009a97b34d1c8b1

**Comment by pdavidc** [comment]
Basic OGC Web Coverage Service (WCS) 1.0.0 elevation coverage support established in commit 965f9ce. Support for the WCS 1.0.0 protocol with single-band coverages in the TIFF response format. The WCS tutorial demonstrates usage. See [WcsElevationFragment.java](https://github.com/NASAWorldWind/WorldWindAndroid/blob/develop/worldwind-tutorials/src/main/java/gov/nasa/worldwindx/WcsElevationFragment.java).
