### ISSUE TITLE
Screen text

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindAndroid#7]
Display of screen facing text from a geographic location. From the COE requirements document: 

Text Annotations 
- Ability to plot a geospatially bound text label that behaves like a point with label, just with no icon. This allows the user to plot text annotations on the map which do not need icons 
- Ability to drape geospatially bound text label on the terrain of the map. The user should have the ability to orient the direction of the text in any direction. 
- Annotation may be set to render in two ways with a property indicating the display method provided in the constructor of the annotation: 
    - Annotation should support draping with rotation. The annotation text is draped over terrain as if it were painted on the ground and is oriented in the direction from the left of the text with a default rotation of 90 degrees to appear as normal text when viewing the map top down with not rotation, tilt, North point up. 
    - Annotation shall support bill boarding so that it floats near the point attached and always faces users view regardless of the globes tilt and rotation

**Comment by pdavidc** [comment]
NASA comments on the COE requirements document: 

WorldWind implements these two capabilities as separate classes, not as one class based on a construction argument. The NASA team has found that this approach makes maintenance and extensibility much more straightforward. With the NASA team’s guidance the application could implement a composite shape that provides this exact behavior, given the built-in WorldWind icon shapes.

**Comment by pdavidc** [comment]
Adding @emxsys as an assignee for development of the label tutorial.

**Comment by emxsys** [comment]
A "Labels Tutorial" was added to the worldwind-tutorials module that demonstrates several facets of label style and placement.

The "Paths and Polygon" example was embellished with Labels in the worldwind-examples module to showcase how labels appear in the context of other shapes.
