### ISSUE TITLE
BlueMarbleLandsatLayer has wrong serviceAddress in constructor

### ISSUE THREAD

**Issue by Sufaev** [NASAWorldWind/WorldWindAndroid#75]
BlueMarble redirect requests from HTTP to HTTPS and this cause BlueMarbleLandsatLayer not working, because ImageRetriever gets 301 text/html error instead of PNG file.

Please. replace http to https in the serviceAddress in constructor and make ImageRetriever able to forward redirects.

Thanks.

**Comment by zglueck** [comment]
The constructor was updated in November 2016 in commit da8a6c7 during our transition to HTTPS services. The master and develop branches are both showing the BlueMarbleLandsatLayer with the HTTPS ```serviceAddress```. @Sufaev have you pulled the latest code or are we missing the change in a different location?

The redirect is an issue we've discussed many times as a team. This [bug report](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4620571) from the URLConnection class indicates Java's decision not to follow protocol portion of the redirect. For the time being, I believe we'll be following their approach with respect to URL redirection by not automatically following redirects. If you have a compelling argument, please let us know!

**Comment by Sufaev** [comment]
Sorry, I have used worldwind.aar downloaded from the web site, not built from git.

Where should I get latest stable version? Is master branch always stable?
