### ISSUE TITLE
ProjectionWGS84 globe and ray intersection calculation providing invalid position and intersect status

### ISSUE THREAD

**Issue by zglueck** [NASAWorldWind/WorldWindAndroid#82]
The intersection calculation which determines if a ray intersects the ellipsoid returns intersections which may occur behind (or in the opposite direction) the ray projection. In some cases, this results in a ray which obviously projects away from globe into space returning a position and intersection calculation success.

**Comment by jgiovino** [comment]
Not sure if this helps…
I have had a great deal of success with this:
https://bitbucket.di2e.net/projects/EMP/repos/emp3-momaps-android/browse/momaps/src/org/mitre/momaps/lib/core/Camera.java#322
may not apply to your ellipse.

Jeff

**Comment by zglueck** [comment]
The method now includes a intersection position check. Intersections behind the origin, as indicated by the direction vector, are ignored.

Closed on 9558e17
