### ISSUE TITLE
Set background to image in WorldWind

### ISSUE THREAD

**Issue by jjfster** [NASAWorldWind/WorldWindAndroid#89]
I cannot find any way to get this to work.  I tried setting the background to a drawable in the globe layout, the parent layout, etc.

I would just like to show the Earth Globe with a star field as a background behind the globe.

Can anyone help?

**Comment by Sufaev** [comment]
Simply pass Custom EGL config with 8888 pixel format and put image view with stars on the background of globe wiev.

**Comment by jjfster** [comment]
I tried using your other issue recommendation:
#57 

In this way:

`<FrameLayout
            android:id="@+id/globe"
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingBottom="1px"
            android:paddingLeft="1px"
            android:paddingRight="1px"
            android:paddingTop="1px"
            android:background="@drawable/stars"
            >`

`   this.wwd = new WorldWindow (this, new WWConfigChooser());
        FrameLayout globeLayout = (FrameLayout) findViewById(R.id.globe);
        globeLayout.addView(this.wwd);
`

I also tried adding the image background to the root view.

Am I doing something wrong?

**Comment by Sufaev** [comment]
Create CustimEGLConfigChooser:
```
public class CustomEGLConfigChooser implements GLSurfaceView.EGLConfigChooser {
    private int config_size = 64;

    @Override
    public EGLConfig chooseConfig(EGL10 egl, EGLDisplay display) {
        int[] attrib_list = {
                EGL10.EGL_RED_SIZE, 8,
                EGL10.EGL_GREEN_SIZE, 8,
                EGL10.EGL_BLUE_SIZE, 8,
                EGL10.EGL_ALPHA_SIZE, 8,
                EGL10.EGL_DEPTH_SIZE, 16,
                EGL10.EGL_NONE
        };

        EGLConfig[] configs = new EGLConfig[config_size];
        int[] num_config = new int[1];
        if (!egl.eglChooseConfig(display, attrib_list, configs, config_size, num_config)) {
            throw new IllegalArgumentException("eglChooseConfig failed");
        }
        config_size = num_config[0];

        EGLConfig config = config_size > 0 ? configs[0] : null;
        if (config == null) {
            throw new IllegalArgumentException("No config chosen");
        }

        return config;
    }
}
```

Than create custom wwd:
```
    public CustomWorldWindow(Context context, Ellipsoid ellipsoid) {
        // Use custom EGLConfigChooser to have possibility to use transparent WorldWind background
        super(context, new CustomEGLConfigChooser());
        // Show WorldWindow always in front of camera video
        setZOrderMediaOverlay(true);
        // Enable transparent background to see camera video
        getHolder().setFormat(PixelFormat.TRANSLUCENT);

```

And put it above the image view on the layout.

**Comment by jjfster** [comment]
I appreciate your help.  Sorry I didn't respond earlier.

I give up.
