### ISSUE TITLE
Path is drowing under the terrain

### ISSUE THREAD

**Issue by Sufaev** [NASAWorldWind/WorldWindAndroid#90]
After implementing WCS terrain support all my Paths on the screen are drown under the terrain, even if I setFollowTerrain (true).

Example on the screenshot.

What am I doind wrong?

![screenshot_2017-04-09-14-08-50](https://cloud.githubusercontent.com/assets/12487306/24836810/9f3c2da4-1d2e-11e7-8a03-e9e51854f2e3.png)

![screenshot_2017-04-09-14-22-38](https://cloud.githubusercontent.com/assets/12487306/24836868/0c0933fe-1d30-11e7-891f-b5bedf04eb4c.png)

**Comment by pdavidc** [comment]
@Sufaev Android paths configured with the CLAMP_TO_GROUND altitudeMode and followTerrain enabled now correctly conform to the terrain. Please try the latest source and let us know how it works for your MIL-STD-2525 tactical graphics use case.

**Comment by Sufaev** [comment]
Yes. Now it works.
In my previous version I have forgotten to setAltitudeMode.
May be it works before too.
